#!/usr/bin/env bash
#a Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid
signt="SIGTERM"
signt="SIGINT"
signq="SIGQUIT"
while true
do
	echo "To infinity and beyond"
	sleep 2
	if [ "$signt" == "SIGTERM" ]
	then
		echo "I hate the kill command"
		rm /var/run/myscript.pid
		exit 0
	elif [ "$signt" == "SIGINT" ]
	then
		echo "Y U no love me?!"
		exit 0
	elif [ "$signq" == "SIGQUIT" ]
	then
		rm /var/run/myscript.pid
                exit 0
	fi
done
