#!/usr/bin/env bash
#a Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	if [ "$signal" == "SIGTERM" ]
	then
		echo "I am invincible!!!"
		continue
	fi
done
