#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
cnt=1
while [ $cnt -le 20 ];
do
	case $cnt in
	4)
		echo "$cnt"
		echo  "bad luck from China"
		;;
	9)
		echo "$cnt"
		echo "bad luck from Japan"
		;;
	17)
		echo "$cnt"
		echo "bad luck from Italy"
		;;
	*)
		echo "$cnt"
		;;
esac
((cnt++))
done
