#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
cnt=0
min=1
while [ $cnt -le 12 ];
do
	echo "Hour: $cnt"
	while [ $min -le 59 ];
	do
		echo "$min"
		((min++))
	done
min=1
((cnt++))
done
