#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#where only the part of the name after the first dash is displayed
list=$(ls)
for v in $list
do
echo "$v" | cut -d- -f 2
done
